# Generated by Django 4.2.2 on 2023-06-16 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='is_deleted',
        ),
    ]
